---
- name: Deploy
  hosts: all
  tasks:

      - name: Git checkout
        ansible.builtin.git:
          repo: 'https://github.com/ijustbsd/ci-test.git'
          dest: /apps/ci-test
          version: master

      - name: Start services
        community.docker.docker_compose:
          project_name: ci-test
          definition:
            version: "3"
            services:
              app:
                image: "{{ image }}"
                restart: always
                ports:
                  - "8000:8000"
          pull: yes
          restarted: yes
