---
- name: Deploy
  hosts: all
  tasks:

      - name: Git checkout
        ansible.builtin.git:
          repo: 'https://github.com/ijustbsd/ci-test.git'
          dest: /apps/ci-test
          version: master
