name: CI

on:
  push:
    branches:
      - master
    
env:
  IMAGE_ID: ghcr.io/${{ github.repository_owner }}/fastapi-app

jobs:

  version:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write
  
    steps:
      - uses: actions/checkout@v2
      
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

  push:

    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          VERSION=${{ steps.semantic.outputs.new_release_version }}

          docker build . --file Dockerfile --tag $IMAGE_ID:$VERSION --tag $IMAGE_ID:latest

      - name: Sign in to the registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push container image
        id: push_container
        run: |
          VERSION=${{ steps.semantic.outputs.new_release_version }}

          docker push $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:latest
          
          echo "::set-output name=image_url::$IMAGE_ID:$VERSION"
  
    outputs:
      image_url: ${{ steps.push_container.outputs.image_url }}

  quality:
    needs:
      - push

    runs-on: ubuntu-latest

    container:
      image: ${{ needs.push.outputs.image_url }}

    steps:

      - name: Run tests
        run: |
          cd /app
          pytest

  deploy:
    needs:
      - push
      - quality

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install ansible plugin
        run: ansible-galaxy collection install community.docker

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/deploy.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            -u ${{ secrets.ANSIBLE_USER }}
            -i ${{ secrets.ANSIBLE_INVENTORY }}
