name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  push:

    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag fastapi-app:latest

      - name: Sign in to the registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push container image
        run: |
          docker tag fastapi-app:latest ghcr.io/${{ github.repository_owner }}/fastapi-app:latest
          docker push ghcr.io/${{ github.repository_owner }}/fastapi-app:latest
